name: srp
description: Secure Remote Password for dart &amp; flutter
version: 1.0.1
homepage: https://github.com/vipycm/srp

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  convert: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  test: 1.16.5

